SUBDIR =
SUBDIR += binutils
SUBDIR += binutils,aarch64
SUBDIR += gcc-bootstrap,arm
SUBDIR += gcc-bootstrap,aarch64
SUBDIR += newlib,arm
SUBDIR += newlib,aarch64
SUBDIR += gcc,arm
SUBDIR += gcc,aarch64
SUBDIR += gdb,arm
SUBDIR += gdb,aarch64

.include <bsd.port.subdir.mk>
